# jekyll-seo-tag
title: "Min Jin Lee"
description: "Official Author site for Min Jin Lee, author of Free Food for Millionaires and Pachinko"
url: "http://www.minjinlee.com" # the base hostname & protocol for your site
author: []
twitter:
  username: minjinlee11
facebook:
  app_id:
  publisher:
  admins:
  link: https://www.facebook.com/minjinleebooks
logo: /uploads/cover-pachinko.jpg
google_site_verification:
github:
  username: budparr
owner: Min Jin Lee

social:
  name: Min Jin Lee
  links:
    - https://www.facebook.com/minjinleebooks/
    - https://www.instagram.com/lee_minjin/
    - https://twitter.com/minjinlee11/




# manifest
short_name: Min Jin Lee
display: fullscreen
future: true

# development meta data
image_url: http://thenewdynamic.imgix.net
google_analytics_id: UA-xxxxx-4
version: 3.0.3
incremental: false
#port: 3575
cloudcannon_id: 23690

bindings:
  hardcover: Hardcover
  paperback: Paperback
  ebook: Ebook
  special: Special Edition

genres:
  fiction: Fiction
  nonfiction: Nonfiction
  poetry: Poetry
  theater: Theater

# Settings
production: true
bust_css_cache: false
full_rebuild: true
timezone: Etc/Zulu
compress_html:
  ignore:
    envs: [development]
  profile: false
gems:
  - jekyll-seo-tag
  - jekyll-archives
plugins_dir:  ./_app/_plugins
layouts_dir:  ./_app/_layouts
includes_dir: ./_app/_includes

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'listing-posts'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/category/:name/'
    category: '/category/:name/'

permalink: pretty

# CONTENT
exclude:
  - readme.md
  - todo.md
  - license.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - node_modules
  - sass
  - gulpfile.js
  - package.json
  - postcss.config.js

collections:
  landing_pages:
    output: true
    permalink: '/:path/'
  books:
    output: true
    permalink: '/:collection/:path/'
  events:
    output: true
    permalink: '/:collection/:path/'
  writings:
    output: true
    permalink: '/:collection/:path/'
  writing_categories:
    output: true
    permalink: '/writing/category/:path/'

defaults:
  - scope:
      path: ''
    values:
      layout: page-single
  - scope:
      path: ''
      type: 'landing_pages'
    values:
      layout: page-single
  - scope:
      path: ''
      type: 'books'
    values:
      layout: book
  - scope:
      path: ''
      type: pages
      permalink: /:basename/
    values:
      layout: page-single
  - scope:
      path: ''
      type: posts
    values:
      layout: page-single
      schema: BlogPosting
  - scope:
      path: ''
      type: events
    values:
      layout: page-single
      category: Events
      _comments:
        title: Event Description
        venue: Venue name. Address is optional




#design
button-classes: ' btn btn-outline col-12 sm-col-auto md-col-auto lg-col-auto mb2 gray border-silver hover-bg-black hover-white transition'
base-layout-classes: ' mx3 sm-mx3 md-mx-auto lg-mx-auto lg-col-6 py2 lg-p3'
base-layout-classes-wide: ' clearfix mx3 sm-mx3 md-mx-auto lg-mx-auto lg-col-9 py2 lg-p3'
base-layout-classes-full: ' col-12 px3'
posting_classes: 'col-12 border-bottom border-divider-color p3 text-decoration-none block py2 secondary-text-color hover-white hover-bg-primary-color transition'
sidebar_item_classes: 'right-align text-decoration-none block px4 py1 primary-text-color hover-white hover-bg-primary-color transition{% if page.url contains category_slug %} bg-primary-color{% endif %}'


fonts_loaded: "'Vesper+Libre:400,500,900'"
font-heading: "'Vesper Libre', 'Merriweather', Georgia, Cambria, 'Times New Roman', Times, serif;"
font-primary: "'Vesper Libre', 'Merriweather', Georgia, Cambria, 'Times New Roman', Times, serif;"
#font-primary: "'Open Sans', 'Avenir Next', 'Lato','Helvetica Neue', Helvetica, -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto',sans-serif;"
font-small: "'Open Sans', 'Avenir Next', 'Lato','Helvetica Neue', Helvetica, -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto',sans-serif;"
font-weight-heavy: '900'

# COLORS
white: "#FFF"
near-white: "#F8F8F8"
silver: "#DDDDDD"
gray:   "#AAAAAA"
light-gray: "#EEE"
dark-gray:  "#333"
black:  "#111111"


primary-color-dark:   "#111"
primary-color:        "#607D8B"
primary-color-light:  "#CFD8DC"
primary-color-text:   "#FFFFFF"
accent-color: "#000" # "#455A64" #  "#D32F2F" #       "#455A64"
primary-text-color:   "#212121"
secondary-text-color: "#757575"
divider-color:        "#BDBDBD"

button-background-color: #var(accent-color)
transparent: transparent



states:
  AK:
   name: Alaska
   abbreviation: AK

  AL:
     name: Alabama
     abbreviation: AL

  AS:
     name: American Samoa
     abbreviation: AS

  AZ:
     name: Arizona
     abbreviation: AZ

  AR:
     name: Arkansas
     abbreviation: AR

  CA:
     name: California
     abbreviation: CA

  CO:
     name: Colorado
     abbreviation: CO

  CT:
     name: Connecticut
     abbreviation: CT

  DE:
     name: Delaware
     abbreviation: DE

  DC:
     name: District of Columbia
     abbreviation: DC

  FM:
     name: Federated States of Micronesia
     abbreviation: FM

  FL:
     name: Florida
     abbreviation: FL

  GA:
     name: Georgia
     abbreviation: GA

  GU:
     name: Guam
     abbreviation: GU

  HI:
     name: Hawaii
     abbreviation: HI

  ID:
     name: Idaho
     abbreviation: ID

  IL:
     name: Illinois
     abbreviation: IL

  IN:
     name: Indiana
     abbreviation: IN

  IA:
     name: Iowa
     abbreviation: IA

  KS:
     name: Kansas
     abbreviation: KS

  KY:
     name: Kentucky
     abbreviation: KY

  LA:
     name: Louisiana
     abbreviation: LA

  ME:
     name: Maine
     abbreviation: ME

  MH:
     name: Marshall Islands
     abbreviation: MH

  MD:
     name: Maryland
     abbreviation: MD

  MA:
     name: Massachusetts
     abbreviation: MA

  MI:
     name: Michigan
     abbreviation: MI

  MN:
     name: Minnesota
     abbreviation: MN

  MS:
     name: Mississippi
     abbreviation: MS

  MO:
     name: Missouri
     abbreviation: MO

  MT:
     name: Montana
     abbreviation: MT

  NE:
     name: Nebraska
     abbreviation: NE

  NV:
     name: Nevada
     abbreviation: NV

  NH:
     name: New Hampshire
     abbreviation: NH

  NJ:
     name: New Jersey
     abbreviation: NJ

  NM:
     name: New Mexico
     abbreviation: NM

  NY:
     name: New York
     abbreviation: NY

  NC:
     name: North Carolina
     abbreviation: NC

  ND:
     name: North Dakota
     abbreviation: ND

  MP:
     name: Northern Mariana Islands
     abbreviation: MP

  OH:
     name: Ohio
     abbreviation: OH

  OK:
     name: Oklahoma
     abbreviation: OK

  OR:
     name: Oregon
     abbreviation: OR

  PW:
     name: Palau
     abbreviation: PW

  PA:
     name: Pennsylvania
     abbreviation: PA

  PR:
     name: Puerto Rico
     abbreviation: PR

  RI:
     name: Rhode Island
     abbreviation: RI

  SC:
     name: South Carolina
     abbreviation: SC

  SD:
     name: South Dakota
     abbreviation: SD

  TN:
     name: Tennessee
     abbreviation: TN

  TX:
     name: Texas
     abbreviation: TX

  UT:
     name: Utah
     abbreviation: UT

  VT:
     name: Vermont
     abbreviation: VT

  VI:
     name: Virgin Islands
     abbreviation: VI

  VA:
     name: Virginia
     abbreviation: VA

  WA:
     name: Washington
     abbreviation: WA

  WV:
     name: West Virginia
     abbreviation: WV

  WI:
     name: Wisconsin
     abbreviation: WI

  WY:
     name: Wyoming
     abbreviation: WY

  AE:
     name: Armed Forces Africa
     abbreviation: AE

  AA:
     name: Armed Forces Americas (except Canada)
     abbreviation: AA

  AE:
     name: Armed Forces Canada
     abbreviation: AE

  AE:
     name: Armed Forces Europe
     abbreviation: AE

  AE:
     name: Armed Forces Middle East
     abbreviation: AE

  AP:
     name: Armed Forces Pacific
     abbreviation: AP
